/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Lead = IDL.Record({
  'submitted' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const NewsletterSubscriber = IDL.Record({
  'email' : IDL.Text,
  'subscribed' : Time,
});

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(NewsletterSubscriber)], ['query']),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'submitted' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const NewsletterSubscriber = IDL.Record({
    'email' : IDL.Text,
    'subscribed' : Time,
  });
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(NewsletterSubscriber)], ['query']),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };